inputconfig:
    collection: sampledata
    credentialfileaddr: firebaseConfig.json
    document: "1"
inputmethod: Firebase
outputconfig:
    collection: sampledata
    credentialfileaddr: firebaseConfig.json
    document: newfirebasedoc
outputmethod: Firebase
