inputconfig:
    queuename: myqueue
    url: amqp://guest:guest@localhost:5672/
inputmethod: RabbitMQ
outputconfig:
    queuename: myqueue
    url: amqp://guest:guest@localhost:5672/
outputmethod: RabbitMQ
