inputconfig:
    ftpfilepath: /home/testuser/testfile.txt
    password: testpass
    url: ftp://localhost:21
    user: testuser
inputmethod: FTP
outputconfig:
    ftpfilepath: /home/testuser/output.txt
    password: testpass
    url: ftp://localhost:21
    user: testuser
outputmethod: FTP
