errorhandling:
    strategy: LOG_AND_CONTINUE
inputconfig:
    csvsourcefilename: sample.csv
inputmethod: CSV
outputconfig:
    csvdestinationfilename: test.csv
outputmethod: CSV
transformations: |
    ADD_FIELD("processed_at", CURRENT_TIME())
validations: |
    FIELD("age") TYPE(INT) RANGE(18, 65)
