inputconfig:
    collection: sampledata
    credentialfileaddr: firebaseConfig.json
    document: "1"
inputmethod: Firebase
outputconfig:
    collection: abcd
    connstring: mongodb://localhost:27017/
    database: test1
outputmethod: MongoDB
transformations: |
    ADD_FIELD("processed_at", '2004-10-22')
validations: |
    FIELD("age") RANGE(30, 35)
