inputconfig:
    collection: fyou
    connstring: mongodb://localhost:27017/
    database: test1
inputmethod: MongoDB
outputconfig:
    collection: abcd
    connstring: mongodb://localhost:27017/
    database: test2
outputmethod: MongoDB
